[package]
name = "aoc-2020-day-08-1"
version = "0.1.0"
authors = ["Ivo Murrell <ivoivo@hey.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
