[package]
name = "aoc_2020_day_01_2"
version = "0.1.0"
authors = ["Ivo Murrell <ivoivo@hey.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.34"
